#!/usr/bin/env python
from math import*
x=float(input("Enter your number:\n"))
n=int(input("Enter the precision:\n"))
def approdeci(x,n):
    appro=floor((x*(10**n)))/(10**n)
    return(appro)
print(approdeci(x,n))
