#!/usr/bin/env python
import math
import matplotlib.pyplot as plt

def analyser_un_seul_point(c, seuil):
    '''
    Calcule le temps de fuite du disque D[centrum=(0;0), R=2] de la suite Z-n(c)
    Temps de fuite majore par seuil.
    Suite Z_n(c) definie par : Z_n(c) = Z_n**2+c
    '''
    zn = 0+0j
    n = 0
    while abs(zn) < 2 and n < seuil:
        zn = zn * zn + c
        n = n + 1
    return n

def analyser_points_de_zone(xmin, xmax, ymin, ymax):
    '''
    Calcule les temps de fuite de la suite (Z_n(c)) pour 400*400 valeurs de
    C comprises dans la zone complexe (xmin, xmax, ymin, ymax).
    Memorise les valeurs dans une matrice 400*400.
    Affiche la matrice en convertissant chaque temps de fuite par une couleur.
    '''
    matrice_temps_de_fuite = [[0 for x in range(400)] for y in range(400) ]
    pasx = (xmax - xmin)/400
    pasy = (ymax - ymin)/400
    for col in range (400):
        print(col, end = '|')
        for lig in range(400):
            reelle = xmin + col * pasx 
            imaginaire = ymax - lig * pasy 
            temps_de_fuite = analyser_un_seul_point(complex(reelle, imaginaire), 1950)
            matrice_temps_de_fuite[lig][col] = temps_de_fuite
    plt.imshow(matrice_temps_de_fuite, cmap = "hvs")

analyser_points_de_zone(-0.743634, -0.743654, 0.131816, 0.131836)
